services:
  - type: web
    name: Maksonbot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: TOKEN
        sync: false
      - key: PYTHON_VERSION
        value: 3.11.10
    build:
      runtime: python3.11
